# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_data_migration_from_old_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AlterField(
            model_name='integration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
