# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170519134547 on 2017-05-19 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170225_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='billing_address',
            new_name='default_billing_address',
        ),
    ]
