# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:25
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
