# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170519134547 on 2017-05-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170519_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
    ]
