# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170519134547 on 2017-05-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20170522_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='address_line_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
