# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170519134547 on 2017-05-22 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='address_line_one',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='address_line_one_check',
            new_name='address_line1_check',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='address_line_two',
            new_name='address_line2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='country',
        ),
    ]
