# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170522191554 on 2017-05-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20170522_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_line1_check',
            field=models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('unavailable', 'Unavailable'), ('unchecked', 'Unchecked')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_zip',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_zip_check',
            field=models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('unavailable', 'Unavailable'), ('unchecked', 'Unchecked')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvc_check',
            field=models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('unavailable', 'Unavailable'), ('unchecked', 'Unchecked')], max_length=12, null=True),
        ),
    ]
