# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170524113944 on 2017-05-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20170523_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_invoice_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
