# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170524113944 on 2017-05-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_customer_last_invoice_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
        ),
    ]
