# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170524113944 on 2017-05-24 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20170524_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
