# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170605150859 on 2017-06-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20170524_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice'),
        ),
    ]
