# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170605150859 on 2017-06-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20170606_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_source',
            field=models.UUIDField(null=True),
        ),
    ]
