# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170605150859 on 2017-06-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20170606_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.Card'),
        ),
    ]
