# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('private', models.BooleanField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'db_table': 'project_server',
            },
        ),
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'projects_users',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectServer', to='servers.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='projectserver',
            unique_together=set([('project', 'server')]),
        ),
    ]
