# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedResource',
            fields=[
                ('folder', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_resources', to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='integrations',
            field=models.ManyToManyField(related_name='projects', through='projects.SyncedResource', to='social_django.UserSocialAuth'),
        ),
    ]
