# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('servers', '0002_auto_20170116_1556'),
        ('users', '0002_data_migration_from_old_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL('''
        ALTER TABLE projects_users
          DROP CONSTRAINT projects_users_user_id_fkey;
        '''),
        migrations.RunSQL('''
        ALTER TABLE projects_users
          RENAME COLUMN user_id TO old_user_id;
        '''),
        migrations.AddField(
            model_name='projectusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectusers',
            unique_together=set([('project', 'user')]),
        ),
        migrations.RunSQL('''
        UPDATE projects_users
          SET user_id = old_user_id;
        '''),
        migrations.RunSQL('''
        ALTER TABLE projects_users
         DROP COLUMN old_user_id;
        '''),
        migrations.RunSQL(
            "UPDATE servers SET project_id=subquery.project_id FROM (SELECT project_id, server_id FROM project_server) AS subquery WHERE id=subquery.server_id;"),
    ]
