# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170225_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncedresource',
            name='url',
        ),
    ]
