# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170116_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
