# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170116_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
