# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-05-12 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170509_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'You can use only alphanumeric characters.')]),
        ),
    ]
