# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:23
from __future__ import unicode_literals

from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from utils import decode_id, encode_id

root = Path(settings.RESOURCE_DIR)


def walk_dir(model, directory, user, project):
    files = []
    for path in directory.iterdir():
        if path.is_dir():
            files.extend(walk_dir(model, path, user, project))
        else:
            files.append(model(
                path=str(path.relative_to(root.joinpath(user.username, encode_id(project.id)))),
                encoding='utf-8',
                author=user,
                project=project,
            ))
    return files


def create_files(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Project = apps.get_model('projects', 'Project')
    File = apps.get_model('projects', 'File')
    for user_dir in root.iterdir():
        if not user_dir.is_dir():
            continue
        db_alias = schema_editor.connection.alias
        user = User.objects.using(db_alias).filter(username=user_dir.name).first()
        if user is not None:
            for project_dir in user_dir.iterdir():
                if not project_dir.is_dir() or str(project_dir).startswith('.'):
                    continue
                project = Project.objects.using(db_alias).filter(id=decode_id(project_dir.name)).first()
                if project is not None:
                    files = walk_dir(File, project_dir, user, project)
                    File.objects.using(db_alias).bulk_create(files)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20170117_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('encoding', models.CharField(max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                             to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                              to='projects.Project')),
            ],
        ),
        migrations.RunPython(create_files, reverse)
    ]
