# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusers',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
