# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170512_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('write_project', 'Write project'), ('read_project', 'Read project'))},
        ),
    ]
