# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170119_1750'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE projects_users ALTER COLUMN id SET DEFAULT nextval('projects_users_id_seq'::regclass);"),
        migrations.AlterUniqueTogether(
            name='projectserver',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='projectserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            "ALTER TABLE project_server ALTER COLUMN id SET DEFAULT nextval('project_server_id_seq'::regclass);"),
    ]
