# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170120_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectserver',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectserver',
            name='server',
        ),
        migrations.RemoveField(
            model_name='project',
            name='servers',
        ),
        migrations.DeleteModel(
            name='ProjectServer',
        ),
    ]
