# -*- coding: utf-8 -*-
# Generated by Django 1.11.3.dev20170619175253 on 2017-06-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=projects.models.user_project_directory_path),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
