# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0003_auto_20170424_1312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('schedule', models.CharField(blank=True, help_text='Cron schedule', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_triggers', to='actions.Action')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_triggers', to='actions.Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
