# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-05-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_auto_20170428_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
