# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20170225_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Canceling'), (3, 'Cancelled'), (4, 'Success'), (5, 'Failed'), (6, 'Created')]),
        ),
    ]
