---

project_name: 3Blades
application_name: threeblades
virtualenv_dir: /vagrant/venv3
app_dir: /vagrant
home_dir: /home/ubuntu
scripts_folder: "{{ home_dir }}/scripts"

# Database settings.
db_user: "{{ application_name }}"
db_name: postgres
db_password:

# env file
database_url: postgres://postgres:@localhost:5432/postgres
is_debug: true
redis_url: redis://localhost:6379/0
django_settings_module: appdj.settings.dev
secret_key: test
docker_host:
rabbitmq_url:
aws_storage_bucket_name:

# Working directory
working_dir: /home/ubuntu

# OpenResty settings.
nginx_server_name: 192.168.10.100
nginx_strong_dh_group: no

# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: admin
rabbitmq_admin_password: password

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password

# Celery settings.
celery_num_workers: 2

# Application settings.
django_settings_file: "appdj.settings.dev"
django_secret_key: "test"

broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

run_django_db_migrations: yes
run_django_collectstatic: yes
