# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:56
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='auto_restart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers',
                                    to='projects.Project'),
        ),
    ]
