# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmenttype',
            name='type',
            field=models.CharField(choices=[('w', 'Workspace'), ('m', 'Model'), ('j', 'Job'), ('d', 'Data source')], max_length=1),
        ),
    ]
