# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170203_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='server',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='server',
        ),
        migrations.RemoveField(
            model_name='environmenttype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='data_sources',
        ),
        migrations.AddField(
            model_name='server',
            name='auto_restart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
