# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170116_1556'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='SshTunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('local_port', models.IntegerField()),
                ('endpoint', models.CharField(max_length=50)),
                ('remote_port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'db_table': 'ssh_tunnel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshtunnel',
            unique_together=set([('name', 'server')]),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
