# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 15:32
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20170119_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='volume_path',
        ),
        migrations.AlterField(
            model_name='environmentresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
