# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20170120_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
