# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20170217_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='type',
        ),
        migrations.AddField(
            model_name='server',
            name='connected',
            field=models.ManyToManyField(related_name='_server_connected_+', to='servers.Server'),
        ),
    ]
