# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-03-28 12:52
from __future__ import unicode_literals

from django.db import migrations


def server_image_names(apps, schema_editor):
    Server = apps.get_model("servers", "Server")
    for server in Server.objects.prefetch_related("environment_type"):
        server.image_name = server.environment_type.image_name
        server.save()


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20170328_1240'),
    ]

    operations = [
        migrations.RunPython(server_image_names, migrations.RunPython.noop),
    ]
