# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-03-28 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20170328_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='environment_type',
        ),
        migrations.DeleteModel(
            name='EnvironmentType',
        ),
    ]
