# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerHost',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=2375)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
